// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfqVJMpBbrT4SEeQRmaNAKAkzt15pNURw',
    appId: '1:349437063430:web:e7209f767374c8b2782e87',
    messagingSenderId: '349437063430',
    projectId: 'aplicativo-cafeteria-curso',
    authDomain: 'aplicativo-cafeteria-curso.firebaseapp.com',
    storageBucket: 'aplicativo-cafeteria-curso.appspot.com',
    measurementId: 'G-BVPQF0H2G0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCk9A8YAExFO1q5LPkhBW_qq6x6_WZTmWI',
    appId: '1:349437063430:android:8c496f748831cea8782e87',
    messagingSenderId: '349437063430',
    projectId: 'aplicativo-cafeteria-curso',
    storageBucket: 'aplicativo-cafeteria-curso.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiivGIwl4LmP8FaBq8u_Et5_QTbz00kqw',
    appId: '1:349437063430:ios:c5ff929bb8523d66782e87',
    messagingSenderId: '349437063430',
    projectId: 'aplicativo-cafeteria-curso',
    storageBucket: 'aplicativo-cafeteria-curso.appspot.com',
    iosClientId: '349437063430-0r68a9s8efgvss1pk41cdfig8dv4ufie.apps.googleusercontent.com',
    iosBundleId: 'com.example.projetocafeteria',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiivGIwl4LmP8FaBq8u_Et5_QTbz00kqw',
    appId: '1:349437063430:ios:7b41d152efda017a782e87',
    messagingSenderId: '349437063430',
    projectId: 'aplicativo-cafeteria-curso',
    storageBucket: 'aplicativo-cafeteria-curso.appspot.com',
    iosClientId: '349437063430-6fhau2kp2slm388fpv3vi10koogg1vbt.apps.googleusercontent.com',
    iosBundleId: 'com.example.projetocafeteria.RunnerTests',
  );
}
